trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md  # Exclude files that don't trigger a build upon change

pr:
  branches:
    include:
      - main  # Set the target branch for pull requests to trigger CI
  paths:
    exclude:
      - README.md  # Exclude files that don't trigger a build upon change

pool:
  name: 'default'
  vmImage: 'OKCOMPUTER'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
